---
# tasks file for nginx

- name: install nginx
  apt: name=nginx state=present

- name: enable service nginx
  service: name=nginx enabled=yes

- name: update nginx sites config
  template: src=nginx-default.conf dest=/etc/nginx/sites-available/default 

- name: restart nginx
  service: name=nginx state=restarted

