---
# tasks file for haproxy

- name: update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: install haproxy
  apt: name=haproxy state=present

- name: enable haproxy
  service: name=haproxy state=started enabled=yes

- name: update HAProxy config
  template: src=haproxy.cfg dest=/etc/haproxy/haproxy.cfg 
  
- name: restart haproxy
  service: name=haproxy state=restarted
